//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8669
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIPS_WMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIPS_WMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        internal static string Greska {
            get {
                return ResourceManager.GetString("Greska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom povezivanja..
        /// </summary>
        internal static string GreskaPovezivanje {
            get {
                return ResourceManager.GetString("GreskaPovezivanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom poziva web servisa..
        /// </summary>
        internal static string GreskaWebServis {
            get {
                return ResourceManager.GetString("GreskaWebServis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime kupca.
        /// </summary>
        internal static string ImeKupca {
            get {
                return ResourceManager.GetString("ImeKupca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedinica.
        /// </summary>
        internal static string Jedinica {
            get {
                return ResourceManager.GetString("Jedinica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedinica mere.
        /// </summary>
        internal static string JedinicaMere {
            get {
                return ResourceManager.GetString("JedinicaMere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina.
        /// </summary>
        internal static string Kolicina {
            get {
                return ResourceManager.GetString("Kolicina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        internal static string Naziv {
            get {
                return ResourceManager.GetString("Naziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv artikla.
        /// </summary>
        internal static string NazivArtika {
            get {
                return ResourceManager.GetString("NazivArtika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepoznat kupac.
        /// </summary>
        internal static string NepoznatKupac {
            get {
                return ResourceManager.GetString("NepoznatKupac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da u okviru podešavanja odaberete štampač..
        /// </summary>
        internal static string NijeOdabranStampac {
            get {
                return ResourceManager.GetString("NijeOdabranStampac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da odaberete artikal!.
        /// </summary>
        internal static string OdaberiteArtikal {
            get {
                return ResourceManager.GetString("OdaberiteArtikal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da odaberete dokument.
        /// </summary>
        internal static string OdaberiteDokument {
            get {
                return ResourceManager.GetString("OdaberiteDokument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da odaberete jedinicu mere!.
        /// </summary>
        internal static string OdaberiteJM {
            get {
                return ResourceManager.GetString("OdaberiteJM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da odaberete liniju iz korpe!.
        /// </summary>
        internal static string OdaberiteLiniju {
            get {
                return ResourceManager.GetString("OdaberiteLiniju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da odaberete štampač..
        /// </summary>
        internal static string OdaberiteStampac {
            get {
                return ResourceManager.GetString("OdaberiteStampac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja nisu sačuvana..
        /// </summary>
        internal static string PodesavanjaNisuSacuvana {
            get {
                return ResourceManager.GetString("PodesavanjaNisuSacuvana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreditni limit je prekoračen!.
        /// </summary>
        internal static string PrekoracenKreditniLimit {
            get {
                return ResourceManager.GetString("PrekoracenKreditniLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raspoloživo.
        /// </summary>
        internal static string Raspolozivo {
            get {
                return ResourceManager.GetString("Raspolozivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra.
        /// </summary>
        internal static string Sifra {
            get {
                return ResourceManager.GetString("Sifra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupno.
        /// </summary>
        internal static string Ukupno {
            get {
                return ResourceManager.GetString("Ukupno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinhronizacija je uspešno završena.\nUkupno kupaca: {0}\nUkupno artikala: {1}.
        /// </summary>
        internal static string UspesnaSinhronizacija {
            get {
                return ResourceManager.GetString("UspesnaSinhronizacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponuda je uspešno kreirana/ažurirana. Broj ponude u NAV-u: {0}.
        /// </summary>
        internal static string UspesnoKreiranjeAzuriranje {
            get {
                return ResourceManager.GetString("UspesnoKreiranjeAzuriranje", resourceCulture);
            }
        }
    }
}
