//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8670
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIPS_WMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIPS_WMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da odaberete artikal!.
        /// </summary>
        internal static string OdaberiteArtikal {
            get {
                return ResourceManager.GetString("OdaberiteArtikal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da odaberete dokument.
        /// </summary>
        internal static string OdaberiteDokument {
            get {
                return ResourceManager.GetString("OdaberiteDokument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da odaberete jedinicu mere!.
        /// </summary>
        internal static string OdaberiteJM {
            get {
                return ResourceManager.GetString("OdaberiteJM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da odaberete liniju iz korpe!.
        /// </summary>
        internal static string OdaberiteLiniju {
            get {
                return ResourceManager.GetString("OdaberiteLiniju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da odaberete štampač..
        /// </summary>
        internal static string OdaberiteStampac {
            get {
                return ResourceManager.GetString("OdaberiteStampac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinhronizacija je uspešno završena.\nUkupno kupaca: {0}\nUkupno artikala: {1}.
        /// </summary>
        internal static string UspesnaSinhronizacija {
            get {
                return ResourceManager.GetString("UspesnaSinhronizacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponuda je uspešno kreirana/ažurirana. Broj ponude u NAV-u: {0}.
        /// </summary>
        internal static string UspesnoKreiranjeAzuriranje {
            get {
                return ResourceManager.GetString("UspesnoKreiranjeAzuriranje", resourceCulture);
            }
        }
    }
}
