//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8669
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8669.
// 
namespace KIPS_WMS.NAV_WS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="KIPS_wms_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms")]
    public partial class KIPS_wms : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public KIPS_wms() {
            this.Url = "http://sqlserver:7047/Wurth/ws/Wurth/Codeunit/KIPS_wms";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:GetQuote", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="GetQuote_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetQuote(string documentNoP, string userIdP, string locationCodeP, ref string customerCodeP, ref string customerNameP, ref int isAuthenticatedCustomerP, ref string cSVStringP) {
            object[] results = this.Invoke("GetQuote", new object[] {
                        documentNoP,
                        userIdP,
                        locationCodeP,
                        customerCodeP,
                        customerNameP,
                        isAuthenticatedCustomerP,
                        cSVStringP});
            customerCodeP = ((string)(results[0]));
            customerNameP = ((string)(results[1]));
            isAuthenticatedCustomerP = ((int)(results[2]));
            cSVStringP = ((string)(results[3]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetQuote(string documentNoP, string userIdP, string locationCodeP, string customerCodeP, string customerNameP, int isAuthenticatedCustomerP, string cSVStringP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetQuote", new object[] {
                        documentNoP,
                        userIdP,
                        locationCodeP,
                        customerCodeP,
                        customerNameP,
                        isAuthenticatedCustomerP,
                        cSVStringP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGetQuote(System.IAsyncResult asyncResult, out string customerCodeP, out string customerNameP, out int isAuthenticatedCustomerP, out string cSVStringP) {
            object[] results = this.EndInvoke(asyncResult);
            customerCodeP = ((string)(results[0]));
            customerNameP = ((string)(results[1]));
            isAuthenticatedCustomerP = ((int)(results[2]));
            cSVStringP = ((string)(results[3]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:SendQuote", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="SendQuote_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendQuote(string userIdP, string locationCodeP, ref string documentNoP, string customerNoP, int isAuthenticatedCustomerP, string cSVStringLinesP, ref int statusP, ref int creditLimitOverdoP) {
            object[] results = this.Invoke("SendQuote", new object[] {
                        userIdP,
                        locationCodeP,
                        documentNoP,
                        customerNoP,
                        isAuthenticatedCustomerP,
                        cSVStringLinesP,
                        statusP,
                        creditLimitOverdoP});
            documentNoP = ((string)(results[0]));
            statusP = ((int)(results[1]));
            creditLimitOverdoP = ((int)(results[2]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendQuote(string userIdP, string locationCodeP, string documentNoP, string customerNoP, int isAuthenticatedCustomerP, string cSVStringLinesP, int statusP, int creditLimitOverdoP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendQuote", new object[] {
                        userIdP,
                        locationCodeP,
                        documentNoP,
                        customerNoP,
                        isAuthenticatedCustomerP,
                        cSVStringLinesP,
                        statusP,
                        creditLimitOverdoP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSendQuote(System.IAsyncResult asyncResult, out string documentNoP, out int statusP, out int creditLimitOverdoP) {
            object[] results = this.EndInvoke(asyncResult);
            documentNoP = ((string)(results[0]));
            statusP = ((int)(results[1]));
            creditLimitOverdoP = ((int)(results[2]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:GetCustomerCreditLimit", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="GetCustomerCreditLimit_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetCustomerCreditLimit(string userIdP, string customerCodeP, ref string creditLimitP, ref string usedCreditLimitP) {
            object[] results = this.Invoke("GetCustomerCreditLimit", new object[] {
                        userIdP,
                        customerCodeP,
                        creditLimitP,
                        usedCreditLimitP});
            creditLimitP = ((string)(results[0]));
            usedCreditLimitP = ((string)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCustomerCreditLimit(string userIdP, string customerCodeP, string creditLimitP, string usedCreditLimitP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCustomerCreditLimit", new object[] {
                        userIdP,
                        customerCodeP,
                        creditLimitP,
                        usedCreditLimitP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGetCustomerCreditLimit(System.IAsyncResult asyncResult, out string creditLimitP, out string usedCreditLimitP) {
            object[] results = this.EndInvoke(asyncResult);
            creditLimitP = ((string)(results[0]));
            usedCreditLimitP = ((string)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:GetItemInformation", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="GetItemInformation_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetItemInformation(string itemNoa47BarCodeP, string variantCodeP, string customerNoP, int isAuthenticatedCustomerP, string locationCodeP, string userIdP, ref string cSVStringP) {
            object[] results = this.Invoke("GetItemInformation", new object[] {
                        itemNoa47BarCodeP,
                        variantCodeP,
                        customerNoP,
                        isAuthenticatedCustomerP,
                        locationCodeP,
                        userIdP,
                        cSVStringP});
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItemInformation(string itemNoa47BarCodeP, string variantCodeP, string customerNoP, int isAuthenticatedCustomerP, string locationCodeP, string userIdP, string cSVStringP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItemInformation", new object[] {
                        itemNoa47BarCodeP,
                        variantCodeP,
                        customerNoP,
                        isAuthenticatedCustomerP,
                        locationCodeP,
                        userIdP,
                        cSVStringP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGetItemInformation(System.IAsyncResult asyncResult, out string cSVStringP) {
            object[] results = this.EndInvoke(asyncResult);
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:GetItemPriceAndInventory", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="GetItemPriceAndInventory_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetItemPriceAndInventory(string itemNoP, string variantCodeP, string unitOfMeasureP, string salesQtyP, string customerNoP, int isAuthenticatedCustomerP, string locationCodeP, string userIdP, ref string cSVStringP) {
            object[] results = this.Invoke("GetItemPriceAndInventory", new object[] {
                        itemNoP,
                        variantCodeP,
                        unitOfMeasureP,
                        salesQtyP,
                        customerNoP,
                        isAuthenticatedCustomerP,
                        locationCodeP,
                        userIdP,
                        cSVStringP});
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItemPriceAndInventory(string itemNoP, string variantCodeP, string unitOfMeasureP, string salesQtyP, string customerNoP, int isAuthenticatedCustomerP, string locationCodeP, string userIdP, string cSVStringP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItemPriceAndInventory", new object[] {
                        itemNoP,
                        variantCodeP,
                        unitOfMeasureP,
                        salesQtyP,
                        customerNoP,
                        isAuthenticatedCustomerP,
                        locationCodeP,
                        userIdP,
                        cSVStringP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGetItemPriceAndInventory(System.IAsyncResult asyncResult, out string cSVStringP) {
            object[] results = this.EndInvoke(asyncResult);
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:GetItemUnitsOfMeasure", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="GetItemUnitsOfMeasure_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetItemUnitsOfMeasure(string itemNoP, string userIdP, ref string cSVStringP) {
            object[] results = this.Invoke("GetItemUnitsOfMeasure", new object[] {
                        itemNoP,
                        userIdP,
                        cSVStringP});
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItemUnitsOfMeasure(string itemNoP, string userIdP, string cSVStringP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItemUnitsOfMeasure", new object[] {
                        itemNoP,
                        userIdP,
                        cSVStringP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGetItemUnitsOfMeasure(System.IAsyncResult asyncResult, out string cSVStringP) {
            object[] results = this.EndInvoke(asyncResult);
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:GetItemLagerList", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="GetItemLagerList_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetItemLagerList(string itemNoP, string variantCodeP, string trackingCodeP, string locationCodeP, ref string cSVStringP) {
            object[] results = this.Invoke("GetItemLagerList", new object[] {
                        itemNoP,
                        variantCodeP,
                        trackingCodeP,
                        locationCodeP,
                        cSVStringP});
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItemLagerList(string itemNoP, string variantCodeP, string trackingCodeP, string locationCodeP, string cSVStringP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItemLagerList", new object[] {
                        itemNoP,
                        variantCodeP,
                        trackingCodeP,
                        locationCodeP,
                        cSVStringP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGetItemLagerList(System.IAsyncResult asyncResult, out string cSVStringP) {
            object[] results = this.EndInvoke(asyncResult);
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:GetItems", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="GetItems_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetItems(ref string cSVStringP, string itemNoP, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime lastDateModifiedP) {
            object[] results = this.Invoke("GetItems", new object[] {
                        cSVStringP,
                        itemNoP,
                        lastDateModifiedP});
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItems(string cSVStringP, string itemNoP, System.DateTime lastDateModifiedP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItems", new object[] {
                        cSVStringP,
                        itemNoP,
                        lastDateModifiedP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGetItems(System.IAsyncResult asyncResult, out string cSVStringP) {
            object[] results = this.EndInvoke(asyncResult);
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:GetCustomers", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="GetCustomers_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetCustomers(ref string cSVStringP, string customerNoP, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime lastDateModifiedP) {
            object[] results = this.Invoke("GetCustomers", new object[] {
                        cSVStringP,
                        customerNoP,
                        lastDateModifiedP});
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCustomers(string cSVStringP, string customerNoP, System.DateTime lastDateModifiedP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCustomers", new object[] {
                        cSVStringP,
                        customerNoP,
                        lastDateModifiedP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGetCustomers(System.IAsyncResult asyncResult, out string cSVStringP) {
            object[] results = this.EndInvoke(asyncResult);
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:GetWarehouseReceipts", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="GetWarehouseReceipts_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetWarehouseReceipts(string userIdP, string locationCodeP, string sublocationCodeP, string itemNoP, ref string cSVStringP) {
            object[] results = this.Invoke("GetWarehouseReceipts", new object[] {
                        userIdP,
                        locationCodeP,
                        sublocationCodeP,
                        itemNoP,
                        cSVStringP});
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetWarehouseReceipts(string userIdP, string locationCodeP, string sublocationCodeP, string itemNoP, string cSVStringP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetWarehouseReceipts", new object[] {
                        userIdP,
                        locationCodeP,
                        sublocationCodeP,
                        itemNoP,
                        cSVStringP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGetWarehouseReceipts(System.IAsyncResult asyncResult, out string cSVStringP) {
            object[] results = this.EndInvoke(asyncResult);
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:GetWarehouseReceiptLines", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="GetWarehouseReceiptLines_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetWarehouseReceiptLines(string userIdP, string locationCodeP, string sublocationCodeP, string whsReceiptNoP, ref string cSVStringP) {
            object[] results = this.Invoke("GetWarehouseReceiptLines", new object[] {
                        userIdP,
                        locationCodeP,
                        sublocationCodeP,
                        whsReceiptNoP,
                        cSVStringP});
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetWarehouseReceiptLines(string userIdP, string locationCodeP, string sublocationCodeP, string whsReceiptNoP, string cSVStringP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetWarehouseReceiptLines", new object[] {
                        userIdP,
                        locationCodeP,
                        sublocationCodeP,
                        whsReceiptNoP,
                        cSVStringP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGetWarehouseReceiptLines(System.IAsyncResult asyncResult, out string cSVStringP) {
            object[] results = this.EndInvoke(asyncResult);
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:GetReceiptLineQtyToReceive", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="GetReceiptLineQtyToReceive_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetReceiptLineQtyToReceive(string userIdP, string whsReceiptNoP, int whsReceiptLineNoP, ref string qtyToReceiveP) {
            object[] results = this.Invoke("GetReceiptLineQtyToReceive", new object[] {
                        userIdP,
                        whsReceiptNoP,
                        whsReceiptLineNoP,
                        qtyToReceiveP});
            qtyToReceiveP = ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetReceiptLineQtyToReceive(string userIdP, string whsReceiptNoP, int whsReceiptLineNoP, string qtyToReceiveP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetReceiptLineQtyToReceive", new object[] {
                        userIdP,
                        whsReceiptNoP,
                        whsReceiptLineNoP,
                        qtyToReceiveP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGetReceiptLineQtyToReceive(System.IAsyncResult asyncResult, out string qtyToReceiveP) {
            object[] results = this.EndInvoke(asyncResult);
            qtyToReceiveP = ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:UpdateWarehouseReceiptLineQty", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="UpdateWarehouseReceiptLineQty_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateWarehouseReceiptLineQty(string userIdP, string whsReceiptNoP, int whsReceiptLineNoP, string qtyP, int isUpdateP, string trackingCSVStringP, string normCSVStringP, string scannedUoMCodeP, string qtyInScannedUoMP) {
            this.Invoke("UpdateWarehouseReceiptLineQty", new object[] {
                        userIdP,
                        whsReceiptNoP,
                        whsReceiptLineNoP,
                        qtyP,
                        isUpdateP,
                        trackingCSVStringP,
                        normCSVStringP,
                        scannedUoMCodeP,
                        qtyInScannedUoMP});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateWarehouseReceiptLineQty(string userIdP, string whsReceiptNoP, int whsReceiptLineNoP, string qtyP, int isUpdateP, string trackingCSVStringP, string normCSVStringP, string scannedUoMCodeP, string qtyInScannedUoMP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateWarehouseReceiptLineQty", new object[] {
                        userIdP,
                        whsReceiptNoP,
                        whsReceiptLineNoP,
                        qtyP,
                        isUpdateP,
                        trackingCSVStringP,
                        normCSVStringP,
                        scannedUoMCodeP,
                        qtyInScannedUoMP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateWarehouseReceiptLineQty(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:UpdateDamagedIncomplete", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="UpdateDamagedIncomplete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateDamagedIncomplete(string userIdP, string documentNoP, int documentLineNoP, string damagedQtyP, string incompleteQtyP) {
            this.Invoke("UpdateDamagedIncomplete", new object[] {
                        userIdP,
                        documentNoP,
                        documentLineNoP,
                        damagedQtyP,
                        incompleteQtyP});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateDamagedIncomplete(string userIdP, string documentNoP, int documentLineNoP, string damagedQtyP, string incompleteQtyP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateDamagedIncomplete", new object[] {
                        userIdP,
                        documentNoP,
                        documentLineNoP,
                        damagedQtyP,
                        incompleteQtyP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateDamagedIncomplete(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:BinToBinMovement", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="BinToBinMovement_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BinToBinMovement(string itemNoP, string qtyAsTxtP, string unitOfMeasureCodeP, string locationCodeP, string sublocationCodeP, string fromBinCodeP, string toBinCodeP, string userIdP, string trackingCSVStringP, ref int nAVLineNoP) {
            object[] results = this.Invoke("BinToBinMovement", new object[] {
                        itemNoP,
                        qtyAsTxtP,
                        unitOfMeasureCodeP,
                        locationCodeP,
                        sublocationCodeP,
                        fromBinCodeP,
                        toBinCodeP,
                        userIdP,
                        trackingCSVStringP,
                        nAVLineNoP});
            nAVLineNoP = ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBinToBinMovement(string itemNoP, string qtyAsTxtP, string unitOfMeasureCodeP, string locationCodeP, string sublocationCodeP, string fromBinCodeP, string toBinCodeP, string userIdP, string trackingCSVStringP, int nAVLineNoP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BinToBinMovement", new object[] {
                        itemNoP,
                        qtyAsTxtP,
                        unitOfMeasureCodeP,
                        locationCodeP,
                        sublocationCodeP,
                        fromBinCodeP,
                        toBinCodeP,
                        userIdP,
                        trackingCSVStringP,
                        nAVLineNoP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndBinToBinMovement(System.IAsyncResult asyncResult, out int nAVLineNoP) {
            object[] results = this.EndInvoke(asyncResult);
            nAVLineNoP = ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:GetItemFromAnotherBin", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="GetItemFromAnotherBin_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetItemFromAnotherBin(ref string linesCSV, string docNo, string lineNo, string userID) {
            object[] results = this.Invoke("GetItemFromAnotherBin", new object[] {
                        linesCSV,
                        docNo,
                        lineNo,
                        userID});
            linesCSV = ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItemFromAnotherBin(string linesCSV, string docNo, string lineNo, string userID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItemFromAnotherBin", new object[] {
                        linesCSV,
                        docNo,
                        lineNo,
                        userID}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGetItemFromAnotherBin(System.IAsyncResult asyncResult, out string linesCSV) {
            object[] results = this.EndInvoke(asyncResult);
            linesCSV = ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:DeleteReclassificationLines", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="DeleteReclassificationLines_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteReclassificationLines(int lineNoP, string userID, string locationCodeP, string sublocationCodeP, int deleteAllLinesP) {
            this.Invoke("DeleteReclassificationLines", new object[] {
                        lineNoP,
                        userID,
                        locationCodeP,
                        sublocationCodeP,
                        deleteAllLinesP});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteReclassificationLines(int lineNoP, string userID, string locationCodeP, string sublocationCodeP, int deleteAllLinesP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteReclassificationLines", new object[] {
                        lineNoP,
                        userID,
                        locationCodeP,
                        sublocationCodeP,
                        deleteAllLinesP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndDeleteReclassificationLines(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:PostReclassification", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="PostReclassification_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PostReclassification(string userIdP, string locationCodeP, string sublocationCodeP, ref int statusP) {
            object[] results = this.Invoke("PostReclassification", new object[] {
                        userIdP,
                        locationCodeP,
                        sublocationCodeP,
                        statusP});
            statusP = ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPostReclassification(string userIdP, string locationCodeP, string sublocationCodeP, int statusP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PostReclassification", new object[] {
                        userIdP,
                        locationCodeP,
                        sublocationCodeP,
                        statusP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPostReclassification(System.IAsyncResult asyncResult, out int statusP) {
            object[] results = this.EndInvoke(asyncResult);
            statusP = ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:GetItemBinContent", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="GetItemBinContent_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetItemBinContent(string userIdP, string locationCodeP, string sublocationCodeP, string binCodeP, string itemNoP, string variantCodeP, ref string cSVStringP) {
            object[] results = this.Invoke("GetItemBinContent", new object[] {
                        userIdP,
                        locationCodeP,
                        sublocationCodeP,
                        binCodeP,
                        itemNoP,
                        variantCodeP,
                        cSVStringP});
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItemBinContent(string userIdP, string locationCodeP, string sublocationCodeP, string binCodeP, string itemNoP, string variantCodeP, string cSVStringP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItemBinContent", new object[] {
                        userIdP,
                        locationCodeP,
                        sublocationCodeP,
                        binCodeP,
                        itemNoP,
                        variantCodeP,
                        cSVStringP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGetItemBinContent(System.IAsyncResult asyncResult, out string cSVStringP) {
            object[] results = this.EndInvoke(asyncResult);
            cSVStringP = ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:ChangeBinOnDocumentLine", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="ChangeBinOnDocumentLine_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ChangeBinOnDocumentLine(string userIdP, int documentTypeP, string documentNoP, int documentLineNoP, string newBinCodeP) {
            this.Invoke("ChangeBinOnDocumentLine", new object[] {
                        userIdP,
                        documentTypeP,
                        documentNoP,
                        documentLineNoP,
                        newBinCodeP});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChangeBinOnDocumentLine(string userIdP, int documentTypeP, string documentNoP, int documentLineNoP, string newBinCodeP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChangeBinOnDocumentLine", new object[] {
                        userIdP,
                        documentTypeP,
                        documentNoP,
                        documentLineNoP,
                        newBinCodeP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndChangeBinOnDocumentLine(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:SplitDocumentLine", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="SplitDocumentLine_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SplitDocumentLine(string userIdP, int documentTypeP, string documentNoP, int documentLineNoP, ref int newDocumentLineNoP) {
            object[] results = this.Invoke("SplitDocumentLine", new object[] {
                        userIdP,
                        documentTypeP,
                        documentNoP,
                        documentLineNoP,
                        newDocumentLineNoP});
            newDocumentLineNoP = ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSplitDocumentLine(string userIdP, int documentTypeP, string documentNoP, int documentLineNoP, int newDocumentLineNoP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SplitDocumentLine", new object[] {
                        userIdP,
                        documentTypeP,
                        documentNoP,
                        documentLineNoP,
                        newDocumentLineNoP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSplitDocumentLine(System.IAsyncResult asyncResult, out int newDocumentLineNoP) {
            object[] results = this.EndInvoke(asyncResult);
            newDocumentLineNoP = ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:TestItemHasTracking", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="TestItemHasTracking_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TestItemHasTracking(string itemNoP, ref int trackingTypeP) {
            object[] results = this.Invoke("TestItemHasTracking", new object[] {
                        itemNoP,
                        trackingTypeP});
            trackingTypeP = ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTestItemHasTracking(string itemNoP, int trackingTypeP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TestItemHasTracking", new object[] {
                        itemNoP,
                        trackingTypeP}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndTestItemHasTracking(System.IAsyncResult asyncResult, out int trackingTypeP) {
            object[] results = this.EndInvoke(asyncResult);
            trackingTypeP = ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:ConvertDecToCommaSepTxtDec", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="ConvertDecToCommaSepTxtDec_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string ConvertDecToCommaSepTxtDec(decimal decimalNumberP) {
            object[] results = this.Invoke("ConvertDecToCommaSepTxtDec", new object[] {
                        decimalNumberP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConvertDecToCommaSepTxtDec(decimal decimalNumberP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConvertDecToCommaSepTxtDec", new object[] {
                        decimalNumberP}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndConvertDecToCommaSepTxtDec(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:ConvertTxtDecToCurrNAVFormat", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="ConvertTxtDecToCurrNAVFormat_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public decimal ConvertTxtDecToCurrNAVFormat(string decimalNumberAsTxtP) {
            object[] results = this.Invoke("ConvertTxtDecToCurrNAVFormat", new object[] {
                        decimalNumberAsTxtP});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConvertTxtDecToCurrNAVFormat(string decimalNumberAsTxtP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConvertTxtDecToCurrNAVFormat", new object[] {
                        decimalNumberAsTxtP}, callback, asyncState);
        }
        
        /// <remarks/>
        public decimal EndConvertTxtDecToCurrNAVFormat(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:ConvertTxtDateToCurrNAVFormat", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="ConvertTxtDateToCurrNAVFormat_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value", DataType="date")]
        public System.DateTime ConvertTxtDateToCurrNAVFormat(string dateAsTxtP) {
            object[] results = this.Invoke("ConvertTxtDateToCurrNAVFormat", new object[] {
                        dateAsTxtP});
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConvertTxtDateToCurrNAVFormat(string dateAsTxtP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConvertTxtDateToCurrNAVFormat", new object[] {
                        dateAsTxtP}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.DateTime EndConvertTxtDateToCurrNAVFormat(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/KIPS_wms:ConvertDateToSRBFormatTxtDate", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", ResponseElementName="ConvertDateToSRBFormatTxtDate_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/KIPS_wms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string ConvertDateToSRBFormatTxtDate([System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateP) {
            object[] results = this.Invoke("ConvertDateToSRBFormatTxtDate", new object[] {
                        dateP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConvertDateToSRBFormatTxtDate(System.DateTime dateP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConvertDateToSRBFormatTxtDate", new object[] {
                        dateP}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndConvertDateToSRBFormatTxtDate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
